sudo -E $(which qemu-system-x86_64) -serial stdio \
   -smp 2,sockets=1,cores=2,threads=1 -m 4096 \
   -device virtio-gpu-pci \
   -display default,show-cursor=on \
   -device qemu-xhci -device usb-kbd \
   -device usb-tablet -device intel-hda \
   -device hda-duplex \
   -drive file=centos_disk_0.img,if=virtio,cache=writethrough \
   -nic user,model=virtio,hostfwd=tcp::10122-:22 \
   -enable-kvm \
   -object memory-backend-file,id=mem,size=4096M,mem-path=/dev/hugepages,share=on \
   -mem-prealloc -numa node,memdev=mem \
   -chardev socket,id=char0,path=/tmp/sock0,server=on \
   -netdev type=vhost-user,id=mynet0,chardev=char0,vhostforce=on \
   -device virtio-net-pci,netdev=mynet0,id=net0,mac=00:00:00:00:00:01